### ISSUE TITLE
Any workaround for new iOS client?

### ISSUE THREAD

**Issue by stevench2000** [ThauEx/ffrk-proxy#123]
ThauEx/folks,
As of this morning, the game (global version) has forced the client to update to the latest version and the proxy no longer works (tried the latest version 0.12.3 already...)
Any workaround for this proxy to somehow still works?
Thanks.

**Comment by ThauEx** [comment]
I don't have an iOS device, so I can't test. Maybe it's similar on android. Havn't played the game for a while...

**Comment by seanbperiod** [comment]
Came here for this - very sad about this, as I thought the legacy app I've been running on iOS 9 hasn't needed to be updated for a very long time. If anyone knows of an old version that still works for iOS please post it here - otherwise, the only way is to use an android device/emulator with proxy. Until then, we may just have to play the game for real! ;) =P

**Comment by rydccoc** [comment]
Seems like Android client doesn't work with the proxy either with the new client :(.  It was a good run!!!

**Comment by rydccoc** [comment]
Android client with proxy log below.

===

ffrk-proxy 0.11.0 started
listening on: 0.0.0.0:5050
rootCA webserver started
listening on: 0.0.0.0:5051
Proxying: GET http://ffrk.denagames.com/dff/splash
Proxying: GET http://127.0.0.1:26284/cache?css_operator=1&ver=t8vLa0a7de843a9e7d721737acd93506880a&url=static/ww/compile/en/css/compile/forAndroid4x/main.css
{ Error: connect ECONNREFUSED 127.0.0.1:26284
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 26284 } [ 'Error: connect ECONNREFUSED 127.0.0.1:26284',
  '    at Object._errnoException (util.js:1024:11)',
  '    at _exceptionWithHostPort (util.js:1046:20)',
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)' ]
Proxying: GET http://127.0.0.1:26284/cache?fail_on_download_error=1&ver=t8vL3cbff6e98cbf7b717b082dffeebbf6b9&url=static/ww/compile/en/js/direct/require.js
{ Error: connect ECONNREFUSED 127.0.0.1:26284
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 26284 } [ 'Error: connect ECONNREFUSED 127.0.0.1:26284',
  '    at Object._errnoException (util.js:1024:11)',
  '    at _exceptionWithHostPort (util.js:1046:20)',
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)' ]
Proxying: GET http://ffrk.denagames.com/favicon.ico

**Comment by seanbperiod** [comment]
Here's a tutorial setting up ffrkproxy.com for android - not sure if they were affected by the update. But if I recall, I think it has something to do with FFRK using HTTPS now: 

https://www.facebook.com/notes/ffrk-proxy-server/faq-for-android/1828322170743038/

**Comment by craadicator** [comment]
Android client still works for me. I am also using Version 0.11.0 with Proxydroid running on my Phone.

**Comment by rydccoc** [comment]
Ah, yeah.  Proxy does work in Android still with version 0.11.0.  The game itself does not launch on the device I was using for FFRK because the OS version is too old.  Whew!  Just have to use a different device.

**Comment by tehtf** [comment]
Think they managed to get iOS working by using proxy.pac to customize the iOS proxy settings and get the ssl certs https://m.facebook.com/notes/ffrk-proxy-server/faq-for-ios-iphone-ipad/2018746865033900/

**Comment by ThauEx** [comment]
I updated the code a bit and at least on android and server running on a mac it was working without any issues.

Since I don't have access to a windows computer to prepare a new release, you have to download the latest 0.12.0 ALPHA and after extrating, replace all files with the ones from master (https://github.com/ThauEx/ffrk-proxy/archive/master.zip)

Also, please check the readme, I updated a few sections. The proxy configuration is now done via pac file.

**Comment by seanbperiod** [comment]
I appreciate your continued work on this! 

I just tried it on iOS and I'm not able to connect. I'm wondering if there's a way to tweak it, similar to how ffrkproxy.com does (as mentioned by @tehtf) , by installing a certificate from charlesproxy?

**Comment by ThauEx** [comment]
Why should this help? This makes no sense at all. It looks like, the "backend" of the other proxy provider is powered by charlesproxy, that why you have to install the certificate.   
As far as I can tell, you don't need a certificate anymore. Just read the updated readme and configure the `proxy.pac`.

**Comment by seanbperiod** [comment]
Ah ok - I got it working on on iOS 9.0.2, but on iOS 11, I continue to get "We're unable to connect, Please check your network settings and try again" system error.

**Comment by ThauEx** [comment]
Looks like the iOS version is using https and android http. Additionally it's not accepting the custom root certificate. I will have a look later...

**Comment by tehtf** [comment]
Hi @Seanbperiod am at work so haven't test out the new build. So the new build works on iOS 9 with latest ffrk now?

**Comment by seanbperiod** [comment]
@tehtf yep. There was a new app update on iOS 9, updated, and it's still working with ffrk-proxy. Same setup doesn't work on iOS 11.
