### ISSUE TITLE
Hello, i have some problem Pls help

### ISSUE THREAD

**Issue by valfaley** [ThauEx/ffrk-proxy#124]
i use this FFRK proxy, it's work fine for me for long time but now have a problem since last week after update app.

when i enter some dungeon or start the battle, the game say "System Error, An error has occurred. Reloading.."

and here proxy log shown
===

Proxying: GET http://ffrk.denagames.com/dff/access_control/get_data
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', sysca
ll: 'read' } [ 'Error: read ECONNRESET',
  '    at _errnoException (util.js:1024:11)',
  '    at TCP.onread (net.js:615:25)' ]
Proxying: GET http://ffrk.denagames.com/dff/access_control/get_data
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', sysca
ll: 'read' } [ 'Error: read ECONNRESET',
  '    at _errnoException (util.js:1024:11)',
  '    at TCP.onread (net.js:615:25)' ]

===

Help Please  ( T-T )

**Comment by tehtf** [comment]
You are using android or iOS?

**Comment by valfaley** [comment]
i'm using android  on  NOX emulator

it's happen since last week, and more often someday i can not play any dungeon
sometimes, can play after 00:00 AM  but still have a problem above to

**Comment by ThauEx** [comment]
Please check this out https://github.com/ThauEx/ffrk-proxy/issues/123#issuecomment-395967571
Maybe it helps.

**Comment by valfaley** [comment]
i try the solution above but still the same 

proxy Log
===========

Proxying: POST http://ffrk.denagames.com/dff/event/extreme/935/get_data_for_worl
d_list
Proxying: GET http://ffrk.denagames.com/favicon.ico
Proxying: GET http://ffrk.denagames.com/dff/access_control/get_data
Proxying: GET http://ffrk.denagames.com/dff/event/wday/607/get_data
Proxying: POST http://ffrk.denagames.com/dff/notification/get_data
Proxying: GET http://ffrk.denagames.com/favicon.ico
Proxying: GET http://ffrk.denagames.com/dff/world/dungeons?world_id=100607
Proxying: POST http://ffrk.denagames.com/dff/notification/get_data
Proxying: GET http://ffrk.denagames.com/favicon.ico
Proxying: GET http://ffrk.denagames.com/dff/access_control/get_data
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', sysca
ll: 'read' } [ 'Error: read ECONNRESET',
  '    at _errnoException (util.js:1024:11)',
  '    at TCP.onread (net.js:615:25)' ]
Proxying: GET http://ffrk.denagames.com/dff/access_control/get_data
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', sysca
ll: 'read' } [ 'Error: read ECONNRESET',
  '    at _errnoException (util.js:1024:11)',
  '    at TCP.onread (net.js:615:25)' ]

==============

or it was because my computer? but i didn't do anything and the proxy work fine for me a year

it had a problem like this before long ago  but just 2 days and then it work fine normally

**Comment by valfaley** [comment]
yesterday it work fine without any error 

but, today it happen again

oh my

**Comment by ThauEx** [comment]
I don't know whats happening. App is newest version? On which OS are you running the proxy?

**Comment by valfaley** [comment]
i'm running on Windows7
it's ok sir, i'll manage my playing
now i'm play after 00:00AM  or in the morning it will less error for me
and thank you very much for your help & answer  ^ ^
