### ISSUE TITLE
updated 0.9.0 but still have problem...JP server...

### ISSUE THREAD

**Issue by bsg313** [ThauEx/ffrk-proxy#63]
I updated 0.9.0
but maybe from last week JP server changed some code or something

still doesn`t work lol

the error massage is like this can U fix this problem?

Proxying: GET http://dff.sp.mbga.jp/dff/battle/?timestamp=1473035138&battle_id=1106110203
Proxying: GET http://dff.static.sp.mbga.jp/dff/static/img/category/tutorial/pic_mog_normal.png?_=1471362061
Proxying: GET http://dff.sp.mbga.jp/dff/battle/get_battle_init_data?crystal=q7PuYLSHWTFMHUoQMdY5p5jn2qfS2rpflbMHygy1WJJ6TdArrkmZfnbEBSKoRB5aIoXb%2F36ztfSnInrJkFJd6H5SKPrmvnjfp%2BqNb1k2iN5VHMAyeFRUeUi%2BnHW5i7OEeQkqJhlvrskbYme60%2FoGMEEYf4e8NMDN9a%2F9UnGJV9Q%3D
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
number of event listener for "battleInitData" 1
C:\Users\Johnny\Downloads\ffrk-proxy-0.9.0-win32-x64\bin\app.js:38
  json.battle.buddy = buddyFilter.update(json.battle.buddy);
                                                    ^

TypeError: Cannot read property 'buddy' of undefined
    at FFRKProxy.<anonymous> (C:\Users\Johnny\Downloads\ffrk-proxy-0.9.0-win32-x64\bin\app.js:38:53)
    at emitTwo (events.js:87:13)
    at FFRKProxy.emit (events.js:172:7)
    at transform (C:\Users\Johnny\Downloads\ffrk-proxy-0.9.0-win32-x64\lib\ffrk-proxy.js:65:21)
    at Gunzip.<anonymous> (C:\Users\Johnny\Downloads\ffrk-proxy-0.9.0-win32-x64\lib\helpers.js:88:5)
    at emitNone (events.js:72:20)
    at Gunzip.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
 계속하려면 아무 키나 누르십시오 . . .

**Comment by Shoukon** [comment]
I am also the same problem
JP Server

**Comment by ThauEx** [comment]
As far as I know, this issue is because they started encrypting the battle data and now we have to find a way to de and encrypt it...
